#!/usr/bin/env python3

# CGI block
import cgi, cgitb ; cgitb.enable()
print ('Content-Type: application/json\nAccess-Control-Allow-Origin: *\n' )
import sqlite3, json, os, sys
conn = sqlite3.connect('myprof.db')

form = cgi.FieldStorage()

yerr = ''

terms = []
try:
  y = form['year'].value
  if '-' in y:
    years = y.split('-')
    yearquery ='(year >="{}" and year <="{}")'.format(years[0], years[1])
  else:
    yearquery = 'year={}'.format(y)
  terms.append(yearquery)
except Exception as err:
  yerr = str(err)
  pass

try:
  schoolquery = 'school like "%{}%"'.format(form['school'].value)
  terms.append(schoolquery)
except:
  pass

try:
  lastnamequery = 'last like "{}%"'.format(form['last'].value)
  terms.append(lastnamequery)
except:
  pass


try:
  firstnamequery = 'first like "{}%"'.format(form['first'].value)
  terms.append(firstnamequery)
except:
  pass

try:
  minsalquery = 'salary >= {}'.format(form['min'].value)
  terms.append(minsalquery)
except:
  pass

try:
  titlequery = 'title like "%{}%"'.format(form['title'].value)
  terms.append(titlequery)
except:
  pass


Query = " and ".join(terms)

if len(terms) == 0:
  jobj = {'status': 405, 'error': 'request must include at least one query'}
  j = json.dumps(jobj)
  print(j)
  sys.exit(2)


try:
  sql = 'select distinct school, first, last, title, salary, taxable, year from profs where {};'.format(Query)
  c = conn.cursor()
  res = c.execute(sql)

  rows = []
  rowDict = {}
  for r in res:
    rowDict = {'school': r[0], 'first':r[1], 'last': r[2], 'title': r[3], 'salary': r[4], 'taxable': r[5], 'year':r[6]}
    rows.append(rowDict)
  count = len(rows)
  jobj =  {'status': 200, 'count': count, 'rows': rows}

  if yerr != '':
    jobj['yerr'] = yerr

  conn.close()

except Exception as e:
  exc_type, exc_obj, exc_tb = sys.exc_info()
  fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
  jobj = {'efname': str(fname), 'elineno': str(exc_tb.tb_lineno) , 'error': str(e), 'status': 500}


j = json.dumps(jobj)

print(j)
